# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='status',
            field=models.CharField(choices=[(b'invited', b'invited'), (b'accepted', b'accepted'), (b'rejected', b'rejected')], default=b'invited', max_length=10),
        ),
    ]
