# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinmedia',
            name='checkin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Checkin'),
        ),
    ]
