# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_checkinmedia_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinmedia',
            name='checkin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='media', to='teams.Checkin'),
        ),
    ]
