# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 20:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0005_auto_20171107_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[(b'sent', b'sent'), (b'delivered', b'delivered'), (b'read', b'read')], max_length=10)),
                ('body', models.TextField()),
                ('original', models.TextField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recv_messages', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teams.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
