# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.CharField(default=1, editable=False, max_length=32),
            preserve_default=False,
        ),
    ]
