# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20171202_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='message_id',
            field=models.CharField(default='1', max_length=40),
            preserve_default=False,
        ),
    ]
