# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_attendance_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='message_id',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
