# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20171204_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='thread',
            field=models.CharField(max_length=32),
        ),
    ]
