# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_auto_20171205_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
