# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDump2',
            new_name='UserDump',
        ),
    ]
