# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-21 11:33
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171104_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.user_photo_path),
        ),
    ]
