# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usermedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedia',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
