# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='user',
            new_name='created_by',
        ),
    ]
