# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20171106_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='session',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
