# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_auto_20171205_0009'),
        ('locations', '0005_phonestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teams.Team'),
        ),
    ]
